baseurl: ""
markdown: kramdown
timezone: Asia/Shanghai

plugins:
  - jekyll-email-protect

collections:
  publications:
    output: true
    permalink: /publications/:path/
  talks:
    output: true
    permalink: /talks/:path/
  news:
    output: false

defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: default
  - scope:
      path: ""
      type: talks
    values:
      layout: default
  - scope:
      path: ""
      type: news
    values:
      layout: default
